### ISSUE TITLE
Does it import models by default?

### ISSUE THREAD

**Issue by dufferzafar** [djk2/django-admin-shell#1]
The django-extensions package comes with a [shell_plus](https://django-extensions.readthedocs.io/en/latest/shell_plus.html) command that imports all models by default.

Does this web shell do the same?

**Comment by djk2** [comment]
Hi. 
I started working on this feature.
Will be ready within few days. 
I have plan for release 2.0 in next week.

**Comment by djk2** [comment]
Autoimport was added to version 1.0.0. 
Behavior of this functionality can be modify by settings described in README. 
The new version introduce a lot of changes, more about it in CHANGELOG file.
