### ISSUE TITLE
bug: about spaces will be converted to &nbsp

### ISSUE THREAD

**Issue by bnm6900030** [djk2/django-admin-shell#5]
I think there should be  html.unescape(code)   before run_code(code)

**Comment by djk2** [comment]
Hi. 
Thanks for your remark and sorry for long absent (I was on leave). 
Can you paste some example here, or write some unit test to expose a bug. 
Will be easier for me to detect and fix the problem. 
Thanks.

**Comment by djk2** [comment]
In my opinion code works fine. 
I manually tested a wide various of cases and I can't find a bug. 
I close issue.
If someone will find a bug case, please inform me.
